StellWorkoutBlog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

# mudando o titulo da pagina admin
admin.site.site_header = 'Administração StellWorkout'

from pages.views import (
    home_view,
    sobre_view,
    stell_wear_view,
    patrocinio_view,
    faq_view,
    termos_e_condicoes_view,
    politica_de_privacidade_view,
)

from account.views import (
    password_reset_form_view,
    registration_view,
    login_view,
    logout_view,
    my_data_view,
    activate_account_view,
    change_password_view,
    del_user_view,
    password_reset_form_view,
    password_reset_new_pass_form,
    toggle_theme_view,
    profile_view,
    notifications_view,
    ajuda_view,
)

from blog.views import (
    posts_view,
    create_post_view,
    search_posts_view,
    unsubscribe_view,
    favourite_post_view,
    favourite_posts_view,
    posts_categoria_view,
    feedback_view,
)

urlpatterns = [
    path('5t3llw0rk0ut4dm1n15tr4c40/', admin.site.urls, name='admin'),
    path('', home_view, name='home'),
    path('register/', registration_view, name="register"),
    path('logout/', logout_view, name="logout"),
    path('login/', login_view, name="login"),
    path('dados/', my_data_view, name="my_data"),
    path('excluir-conta/', del_user_view, name='del_user'),
    path('activate/<uidb64>/<token>', activate_account_view, name='activate'),
    path('alterar-senha/', change_password_view, name='change_password'),
    path('posts/', posts_view, name='posts'),
    path('novo-post/', create_post_view, name='novo_post'),
    path('search-posts/', search_posts_view, name='search_posts'),
    path('unsubscribe/<uidb64>/<token>', unsubscribe_view, name='unsubscribe'),
    path('mudar-senha', password_reset_form_view, name='password_reset'),
    path('mudar-senha-redefinir/<uidb64>/<token>', password_reset_new_pass_form, name='password_reset_new_pass'),
    path('<id>/favourite-post/', favourite_post_view, name='favourite_post'),
    path('favourite-posts/', favourite_posts_view, name='favourite_posts'),
    path('posts/<categoria>', posts_categoria_view, name='posts_categoria'),
    path('toggle-theme/', toggle_theme_view, name='toggle_theme'),
    path('feedback/', feedback_view, name='feedback'),
    path('perfil/', profile_view, name='profile'),
    path('notificacoes/', notifications_view, name='notificacoes'),
    path('ajuda/', ajuda_view, name='ajuda'),
    path('sobre/', sobre_view, name='sobre'),
    path('stell-wear/', stell_wear_view, name='stell_wear'),
    path('patrocinio/', patrocinio_view, name='patrocinio'),
    path('faq/', faq_view, name='faq'),
    path('termos-e-condicoes/', termos_e_condicoes_view, name='termos_e_condicoes'),
    path('politica-de-privacidade/', politica_de_privacidade_view, name='politica_de_privacidade'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from slugify import slugify
from account.models import Account
from PIL import Image
import os
import uuid

POST_IMAGE_ASPECT_RATIO = 1.4479 # height / width
POST_IMAGE_MAX_WIDTH = 350 # largura max da imagem do post (em px)

def wrapper(instance, filename):
    # wrapper para o arquivo (pdf) do post
    ext = filename.split('.')[-1]
    filename = '{}-{}.{}'.format(slugify(instance.title), uuid.uuid4(), ext)
    return os.path.join('posts', filename)

def image_wrapper(instance, filename):
    # wrapper para o arquivo de imagem do post
    ext = filename.split('.')[-1]
    filename = '{}-{}.{}'.format(slugify(instance.title), uuid.uuid4(), ext)
    return os.path.join('post_images', filename)


class Category(models.Model):
    name = models.CharField(max_length=25, verbose_name='Nome')
    readable_name = models.CharField(max_length=25, verbose_name='Nome legível')
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.readable_name

    class Meta:
        verbose_name_plural = 'categories'


class Post(models.Model):
    title = models.CharField(max_length=255, verbose_name='Título')
    intro = models.TextField(verbose_name='Introdução')
    file = models.FileField(upload_to=wrapper, verbose_name='Arquivo')
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)
    categories = models.ManyToManyField(Category, related_name='posts', blank=True)
    image = models.ImageField(default='post_images/default.png', upload_to=image_wrapper, verbose_name='Imagem')
    favourite = models.ManyToManyField(Account, related_name='favourite', blank=True)

    def save(self, *args, **kwargs):
        # corrigindo o tamanho da imagem ao salvar
        super().save()

        img = Image.open(self.image.path)

        width = img.width

        if width > POST_IMAGE_MAX_WIDTH:
            width = POST_IMAGE_MAX_WIDTH # tamanho max permitido para as imagens

        output_size = (width, width*POST_IMAGE_ASPECT_RATIO)
        img.thumbnail(output_size)
        img.save(self.image.path)

    def delete(self, using=None, keep_parents=False):
        self.file.storage.delete(self.file.name)
        self.image.storage.delete(self.image.name)
        super().delete()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-date_added']


   

blog/forms.py
from django import forms
from blog.models import Post

class CreatePostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'categories', 'intro', 'file', 'image']
        

blog/views.py
from django.conf import settings
from django.http.response import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.sites.shortcuts import get_current_site
from account.models import Account
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text
from .utils import generate_token
from django.http import Http404
from django.contrib.postgres.search import SearchQuery, SearchVector
from .utils import posts_matrix, email_notification, feedback_email
from .models import Post, Category
from .forms import CreatePostForm

def posts_view(request):
    context = {}

    user = request.user

    if not user.is_authenticated:
        return redirect('home')
    else:
        posts = Post.objects.order_by('-date_added')
        favourite_posts = user.favourite.all()
        context['todos_posts'] = posts
        context['categorias'] = []
        context['favourite_posts'] = favourite_posts

        categorias = Category.objects.all()

        for categoria in categorias:
            posts_categoria = categoria.posts.all()
            if posts_categoria:
                context['categorias'].append((categoria.name.replace('_', '-'), categoria.readable_name, posts_categoria))
        
        return render(request, 'blog/posts.html', context)


def create_post_view(request):
    context = {}

    user = request.user

    if not user.is_admin:
        return redirect('home')

    if request.POST:
        form_novo_post = CreatePostForm(request.POST, request.FILES)
    else:    
        form_novo_post = CreatePostForm()

    if form_novo_post.is_valid():
        obj = form_novo_post.save(commit=False)
        obj.user = user
        obj.save()
        form_novo_post.save_m2m()
        messages.success(request, f'O post foi enviado com sucesso!')

        if request.POST.get('notification') and ((not settings.DEBUG) or settings.SEND_MAILS):
            domain = get_current_site(request)
            email_notification(obj, domain) # mandando email com notificação

        return redirect('home')

    context['form_novo_post'] = form_novo_post

    return render(request, 'blog/novo_post.html', context)
    

def search_posts_view(request):
    context = {}

    user = request.user

    if not user.is_authenticated:
        return redirect('home')
    
    if request.method == "POST":
        searched = request.POST.get('searched', False)
        context['searched'] = searched

        query = SearchQuery(searched)
        vector = SearchVector('title', 'intro')

        posts = Post.objects.annotate(
            search=vector,
        ).filter(search=query)

        num_posts = len(posts)
        posts_mtx = posts_matrix(posts)
        favourite_posts = user.favourite.all()
        context['posts_mtx'] = posts_mtx
        context['num_posts'] = num_posts
        context['favourite_posts'] = favourite_posts

        return render(request, 'blog/search_posts.html', context)
    else:
        return redirect('home')


def unsubscribe_view(request, uidb64, token):
    # remove um usuario da lista de emails
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = Account.objects.get(pk=uid)
    except Exception as identifier:
        user = None
    
    if user is not None and generate_token.check_token(user, token):
        user.subscriber = False
        user.save()
        messages.info(request, f'Você não receberá mais emails.')
        return redirect('home')

    return render(request, 'blog/unsubscribe_failed.html', status=401)


def favourite_post_view(request, id):
    post = get_object_or_404(Post, id=id)
    if post.favourite.filter(id=request.user.id).exists():
        post.favourite.remove(request.user)
    else:
        post.favourite.add(request.user)

    return HttpResponse('')

def favourite_posts_view(request):
    context = {}

    user = request.user

    if not user.is_authenticated:
        return redirect('home')

    posts = user.favourite.all()
    posts_mtx = posts_matrix(posts)
    num_posts = len(posts)
    favourite_posts = user.favourite.all()
    context['favourite_posts'] = favourite_posts
    context['num_posts'] = num_posts
    context['posts_mtx'] = posts_mtx

    return render(request, 'blog/favourite_posts.html', context)


def posts_categoria_view(request, categoria):
    context = {}

    user = request.user

    if not user.is_authenticated:
        return redirect('home')
    else:
        if not categoria == 'todos':
            categoria_name = categoria.replace('-', '_')
            categoria_obj = get_object_or_404(Category, name=categoria_name)
            categoria_verbose = categoria_obj.readable_name
            posts = categoria_obj.posts.all()
        else:
            categoria_verbose = 'Todos'
            posts = Post.objects.all()
            
        favourite_posts = user.favourite.all()
        posts_mtx = posts_matrix(posts)
        context['posts_mtx'] = posts_mtx
        context['categoria_verbose'] = categoria_verbose
        context['favourite_posts'] = favourite_posts
        context['num_posts'] = len(posts)
        
        return render(request, 'blog/posts_categoria.html', context)


def feedback_view(request):
    context = {}
    
    if request.method == "POST":
        nome = request.POST.get('nome', False)
        email = request.POST.get('email', False)
        mensagem = request.POST.get('mensagem', False)

        if (not settings.DEBUG) or settings.SEND_MAILS:
            feedback_email(nome, email, mensagem)

        messages.success(request, f'Sua mensagem foi enviada!')
        return redirect('home')
    else:
        return redirect('home')

blog/templates/blog/favourite_posts.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
{% endblock head %}

{% block content %}

    <div class="container content-container">

        {% if not num_posts > 0 %}
            <h5>Você ainda não possui nenhum post favorito!</h5>
        {% else %}
            <h3 class="titulo-categoria">Favoritos</h3><br>
            {% for line in posts_mtx %}
                <div class="row blog-grid-row">
                    {% for post in line %}
                    <div class="col s6 m3 l3">
                        <div class="card hoverable post-card hover-reveal" style="background-image: url({{ post.image.url }});">
                            <div class="right top favourite-button"
                            id="favourite_button_{{ post.id }}"
                            style="-moz-user-select: none; -webkit-user-select: none; -ms-user-select:none; user-select:none;-o-user-select:none;" 
                            unselectable="on"
                            onselectstart="return false;" 
                            onmousedown="return false;">
                                {% if  post in favourite_posts %}
                                    <i class="material-icons saved">bookmark</i>
                                {% else %}
                                    <i class="material-icons">bookmark</i>
                                {% endif %}
                                <span class="post-id" style="display: none;">{{ post.id }}</span>
                            </div>
                            <div class="card-content">
                                <span class="card-title activator"><a href="{{ post.file.url }}" target="_blank" class="post-link"><h5>{{ post.title }}</h4></a></span>
                            </div>
                            <div class="card-reveal" style="background-color: rgba(41, 41, 41, 0.6);">
                                <p>{{ post.intro }}</p>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            {% endfor %}
        {% endif %}
    </div>
    
{% endblock content %}

{% block js %}
    <script src="{% static 'blog/js/script.js' %}"></script>
{% endblock js %}

blog/templates/blog/novo_post.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
{% endblock head %}

{% block content %}

    <div class="row form-container">
        <div class="col s12 m8 offset-m2">
            <div class="card form-card">
                <div class="card-action grey lighten-2">
                    <h3>Novo Post</h3>
                </div>
                <div class="card-content">
                    <form action="" method="post" enctype="multipart/form-data" class="form-card-form">
                        {% csrf_token %}

                        {% for field in form_novo_post %}
                            <div class="row">
                                {% if not field.name == 'file' and not field.name == 'image' %}
                                    <div class="input-field col s12">
                                        {{ field }}
                                        {{ field.label_tag }}
                                        {% for error in field.errors %}
                                            <p class="error-message-field">{{ error }}</p>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {% if field.name == 'file' %}
                                        <div class="file-field input-field col s12">
                                            <div class="btn grey lighten-2 black-text">
                                                <span><i class="left material-icons">attach_file</i>Arquivo</span>
                                                {{ field }}
                                            </div>
                                            <div class="file-path-wrapper">
                                                <input type="text" class="file-path validate">
                                            </div>
                                            {% for error in field.errors %}
                                                <p class="error-message-field">{{ error }}</p>
                                            {% endfor %}
                                        </div>
                                    {% else %}
                                        <div class="file-field input-field col s12">
                                            <div class="btn grey lighten-2 black-text">
                                                <span><i class="left material-icons">image</i>Imagem</span>
                                                {{ field }}
                                            </div>
                                            <div class="file-path-wrapper">
                                                <input type="text" class="file-path validate">
                                            </div>
                                            {% for error in field.errors %}
                                                <p class="error-message-field">{{ error }}</p>
                                            {% endfor %}
                                        </div>
                                    {% endif %}
                                {% endif %}
                            </div>
                        {% endfor %}
                        <p>
                            <label>
                                <input type="checkbox" name="notification" id="notification" value="notification">
                                <span>Notificar usuários</span>
                            </label>
                        </p><br>
                        

                        {% if form_novo_post.non_field_errors %}
                            <div class="non-field-error">
                                <p>{{ form_novo_post.non_field_errors }}</p>
                            </div>
                        {% endif %}
                        <button class="btn-large grey lighten-2 black-text waves-effect waves-dark" style="width:100%">Enviar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script>
        var intro = document.querySelector('#id_intro');
        intro.classList.add('materialize-textarea')
    </script>

{% endblock content %}

blog/templates/blog/novo_post_email.html
{% autoescape off %}

<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600&display=swap" rel="stylesheet">

<style>
    h3 {
        text-align: center;
    }
    .email-wrapper {
        text-align: center;
        max-width: 85%;
        margin: auto;
        border: solid 1px black;
        font-family: 'Poppins';
    }
</style>

<div class="email-wrapper">
    <h3>Olá {{ user.username }}!</h3>
    <p>Temos conteúdo novo para você. Confira o novo post em nosso site, clicando no link abaixo.</p>
    <p>http://{{ domain }}{{ post.file.url }}</p>
    <br><p>Caso não queira mais receber emails, clique no link abaixo.</p>
    <p>http://{{ domain }}{% url 'unsubscribe'  uidb64=uid token=token %}</p>
</div>

{% endautoescape %}

blog/templates/blog/posts.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
{% endblock head %}

{% block content %}

    <div class="container content-container">
        <h3 class="titulo-categoria"><a href="{% url 'posts_categoria' categoria='todos' %}">Todos</a></h3>
        <div class="carousel-wrap">
            <div class="owl-carousel owl-theme posts-carousel">
                {% for post in todos_posts %}
                    <div class="card hoverable post-card hover-reveal" data-merge="2" style="background-image: url({{ post.image.url }});">
                        <div class="right top favourite-button"
                        id="favourite_button_{{ post.id }}"
                        style="-moz-user-select: none; -webkit-user-select: none; -ms-user-select:none; user-select:none;-o-user-select:none;" 
                        unselectable="on"
                        onselectstart="return false;" 
                        onmousedown="return false;">
                            {% if  post in favourite_posts %}
                                <i class="material-icons saved">bookmark</i>
                            {% else %}
                                <i class="material-icons">bookmark</i>
                            {% endif %}
                            <span class="post-id" style="display: none;">{{ post.id }}</span>
                        </div>
                        <div class="card-content">
                            <span class="card-title activator fill-div"><a href="{{ post.file.url }}" target="_blank" class="post-link fill-div"><h5>{{ post.title }}</h4></a></span>
                        </div>
                        <div class="card-reveal" style="background-color: rgba(41, 41, 41, 0.6);">
                            <p>{{ post.intro }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

        {% for categoria, verbose_name, posts_categoria in categorias %}
            
            <h3 class="titulo-categoria"><a href="{% url 'posts_categoria' categoria=categoria %}">{{ verbose_name }}</a></h3>
            
            <div class="owl-carousel owl-theme posts-carousel">
                {% for post in posts_categoria %}
                    <div class="card hoverable post-card hover-reveal" data-merge="2" style="background-image: url({{ post.image.url }});">
                        <div class="right top favourite-button"
                        id="favourite_button_{{ post.id }}"
                        style="-moz-user-select: none; -webkit-user-select: none; -ms-user-select:none; user-select:none;-o-user-select:none;" 
                        unselectable="on"
                        onselectstart="return false;" 
                        onmousedown="return false;">
                            {% if  post in favourite_posts %}
                                <i class="material-icons saved">bookmark</i>
                            {% else %}
                                <i class="material-icons">bookmark</i>
                            {% endif %}
                            <span class="post-id" style="display: none;">{{ post.id }}</span>
                        </div>
                        <div class="card-content">
                            <span class="card-title activator"><a href="{{ post.file.url }}" target="_blank" class="post-link"><h5>{{ post.title }}</h4></a></span>
                        </div>
                        <div class="card-reveal" style="background-color: rgba(41, 41, 41, 0.6);">
                            <p>{{ post.intro }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
    </div>

{% endblock content %}

{% block js %}
    <script src="{% static 'blog/js/script.js' %}"></script>
{% endblock js %}

blog/templates/blog/posts_categoria.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
{% endblock head %}

{% block content %}

    <div class="container content-container">
        {% if not num_posts > 0 %}
            <h5>Ainda não existem posts da categoria <strong>"{{ categoria_verbose }}".</strong></h5>
        {% else %}
            <h3 class="titulo-categoria">{{ categoria_verbose }}</h3><br>
            {% for line in posts_mtx %}
                <div class="row blog-grid-row">
                    {% for post in line %}
                        <div class="col s6 m3 l3">
                            <div class="card hoverable post-card hover-reveal" style="background-image: url({{ post.image.url }});">
                                <div class="right top favourite-button"
                                id="favourite_button_{{ post.id }}"
                                style="-moz-user-select: none; -webkit-user-select: none; -ms-user-select:none; user-select:none;-o-user-select:none;" 
                                unselectable="on"
                                onselectstart="return false;" 
                                onmousedown="return false;">
                                    {% if  post in favourite_posts %}
                                        <i class="material-icons saved">bookmark</i>
                                    {% else %}
                                        <i class="material-icons">bookmark</i>
                                    {% endif %}
                                    <span class="post-id" style="display: none;">{{ post.id }}</span>
                                </div>
                                <div class="card-content">
                                    <span class="card-title activator"><a href="{{ post.file.url }}" target="_blank" class="post-link"><h5>{{ post.title }}</h4></a></span>
                                </div>
                                <div class="card-reveal" style="background-color: rgba(41, 41, 41, 0.6);">
                                    <p>{{ post.intro }}</p>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% endfor %}
        {% endif %}
        
    </div>

{% endblock content %}

{% block js %}
    <script src="{% static 'blog/js/script.js' %}"></script>
{% endblock js %}

blog/templates/blog/search_posts.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
{% endblock head %}

{% block content %}

    <div class="container content-container">
        {% if searched %}
            {% if not num_posts > 0 %}
                <i><h5 class="search-result">Não foram encontrados resultados para <b>"{{ searched }}".</b></h5></i>
            {% else %}
                <i><h5 class="search-result">{% if not num_posts == 1 %}Foram encontrados{% else %}Foi encontrado{% endif %} {{ num_posts }} resultado{% if not num_posts == 1 %}s{% endif %} para <b>"{{ searched }}"</b>:</h5></i><br>
                {% for line in posts_mtx %}
                    <div class="row blog-grid-row">
                        {% for post in line %}
                            <div class="col s6 m3 l3">
                                <div class="card hoverable post-card hover-reveal" style="background-image: url({{ post.image.url }});">
                                    <div class="right top favourite-button"
                                    id="favourite_button_{{ post.id }}"
                                    style="-moz-user-select: none; -webkit-user-select: none; -ms-user-select:none; user-select:none;-o-user-select:none;" 
                                    unselectable="on"
                                    onselectstart="return false;" 
                                    onmousedown="return false;">
                                        {% if  post in favourite_posts %}
                                            <i class="material-icons saved">bookmark</i>
                                        {% else %}
                                            <i class="material-icons">bookmark</i>
                                        {% endif %}
                                        <span class="post-id" style="display: none;">{{ post.id }}</span>
                                    </div>
                                    <div class="card-content">
                                        <span class="card-title activator"><a href="{{ post.file.url }}" target="_blank" class="post-link"><h5>{{ post.title }}</h4></a></span>
                                    </div>
                                    <div class="card-reveal" style="background-color: rgba(41, 41, 41, 0.6);">
                                        <p>{{ post.intro }}</p>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                {% endfor %}
            {% endif %}
        {% else %}
            <h5>Insira um termo para pesquisar.</h5>
        {% endif %}
        
    </div>

{% endblock content %}

{% block js %}
    <script src="{% static 'blog/js/script.js' %}"></script>
{% endblock js %}

blog/templates/blog/unsubscribe_failed.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
{% endblock head %}

{% block content %}

    <div class="container content-container">
        <h5>Link expirado. Sua inscrição possivelmente já foi cancelada anteriormente através deste link.</h5>
    </div>

{% endblock content %}